spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3307/mmc
    username: root
    password: Root88*
  server:
    port: 8080
    ssl:
      enabled: false