spring:
  config:
    activate:
      on-profile: oauth
  security:
    oauth2:
      client:
        registration: ## OAuth2 클라이언트(내 애플리케이션)가 소셜 로그인 제공자로부터 발급받은 정보를 설정
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_REDIRECT_URI}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
              - openid