spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://144.24.79.37:3306/mmc
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  server:
    port: 443
    ssl:
      enabled: true
      key-store: /app/keystore.p12
      key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
      key-store-type: PKCS12
      key-alias: tomcat
      trust-store: file:/usr/lib/jvm/java-17-openjdk/lib/security/cacerts
      trust-store-password: changeit
      trust-store-type: JKS