# 공통 설정
spring:
  main:
    lazy-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    layout-decorator: layouts/default
  management:
    endpoint:
      health:
        enabled: true
        show-details: always
    endpoints:
      web:
        exposure:
          include: health

# 로깅 설정 추가
logging:
  level:
    org.springframework: DEBUG
    org.springframework.boot: DEBUG
    org.springframework.boot.web.embedded.tomcat: DEBUG

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# JWT 설정
jwt:
  secret: "D72jNk@dG73slP@Ue94R&ZgJ69Fn!Lr@wP$Yb7xQ2wF9nSb5Q"