# JPA 설정
spring: # spring.datasource : SpringBoot의 JPA와 관련된 DB 연결 정보를 설정하는 곳
  main:
    lazy-initialization: true  # 빈 초기화를 지연시켜 시작 시간 단축
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://144.24.79.37:3306/mmc}  # 환경 변수 사용, 기본값은 VM MySQL
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Root88**}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # 엔티티와 테이블의 일치여부만 확인하고, 변경하지 않음
  profiles:
    include: oauth
  server:
    port: 8080
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    layout-decorator: layouts/default

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml  # XML 매퍼 위치
  configuration:
    map-underscore-to-camel-case: true  # DB 컬럼명 CamelCase로 자동 변환

# JWT 설정
jwt:
  secret: "D72jNk@dG73slP@Ue94R&ZgJ69Fn!Lr@wP$Yb7xQ2wF9nSb5Q"