spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  main:
    lazy-initialization: true
  profiles:
    include: oauth
  jpa:
    hibernate:
      ddl-auto: validate  # 배포 환경에서는 validate 권장
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    layout-decorator: layouts/default
  management:
    endpoint:
      health:
        enabled: true
        show-details: always
    endpoints:
      web:
        exposure:
          include: health
  server:
    port: ${SERVER_PORT:8080}

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# JWT 설정
jwt:
  secret: "D72jNk@dG73slP@Ue94R&ZgJ69Fn!Lr@wP$Yb7xQ2wF9nSb5Q"