name: MMC CI/CD

on:
  push:
    branches:
      - main  # main 브랜치에 푸시 시 실행

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub의 Ubuntu 가상 머신에서 실행
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 저장소 코드를 가져옴
      - name: Print message
        run: echo "Hello, MMC CI/CD is running!"
